# Generated by Django 4.1.1 on 2022-10-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learning",
            name="description",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="prerequisite",
            name="description",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=models.CharField(max_length=100),
        ),
    ]
