# Generated by Django 4.1.1 on 2022-10-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_video_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="course", name="name", field=models.CharField(max_length=50),
        ),
    ]
