# Generated by Django 4.1.1 on 2022-10-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_course_slug_alter_course_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course", name="slug", field=models.CharField(max_length=50),
        ),
    ]
