# Generated by Django 4.1.1 on 2022-10-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_course_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
