# Generated by Django 4.1.1 on 2022-11-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_usercourse_payment"),
    ]

    operations = [
        migrations.DeleteModel(name="Payment",),
    ]
